# Numpy Basics

In [2]:
import numpy as np

x = np.array([1,2,3,4,5],np.int16) # 1-Dimensional ndArray


In [4]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print(x[0]); print(x[1]); print(x[2])

1
2
3


In [6]:
print(x[-1]) # print last element of ndarray

5


In [9]:
y = np.array([[1,2,3],[4,5,6]],np.int16) # 2D ndarray
print(y)

[[1 2 3]
 [4 5 6]]


In [12]:
print(y[0,0]); print(y[0,1]); print(y[0,2]);

1
2
3


In [19]:
print(y[:,0])# Entire 1st column  will get printed

[1 4]


In [20]:
print(y[:,2])# Entire 3st column  will get printed

[3 6]


In [18]:
print(y[0,:]) # Entire 1st row  will get printed

[1 2 3]


In [4]:
x = np.array([[[1,2,3],[4,5,6]],[[0,-1,-2],[-3,-4,-5]]],np.int16) # 3D ndarray
print(x)
print(x.shape)
print(x.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]
(2, 2, 3)
3


### Accessing element of 3d ndarray

In [23]:
print(x[0,0,0])

1


In [26]:
print(x[0,1,2])

6


In [29]:
print(x[:, :,1]) # printing entire column

[[ 2  5]
 [-1 -4]]


## Numpy Ndarray Properties

In [2]:
import numpy as np
x = np.array([[[1,2,3],[4,5,6],[0,-1,-2]]],np.int16)
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 0 -1 -2]]]


In [36]:
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.size)
print(x.nbytes) #Consumption of bytes in ram of sysytem

(2, 2, 3)
3
int16
12
24


In [38]:
print(x.T) # transpose of numpy array

[[[ 1  0]
  [ 4 -3]]

 [[ 2 -1]
  [ 5 -4]]

 [[ 3 -2]
  [ 6 -5]]]


## Array Manipuation Routine

In [40]:
x = np.array([[1,2,3],[4,5,6]],np.int16) # 2D ndarray
print(x)

[[1 2 3]
 [4 5 6]]


In [42]:
y = np.reshape(x,6)
print(y)

[1 2 3 4 5 6]


In [43]:
y = np.ravel(x)
print(y)

[1 2 3 4 5 6]


In [ ]:
f = x.flatten() # Default
print(f)

In [47]:
f = x.flatten('C') # Row wise flattening
print(f)

[1 2 3 4 5 6]


In [46]:
f = x.flatten('F') # column wise flattening
print(f)

[1 4 2 5 3 6]


In [ ]:
z=np.y.reshape(0,DescriptorSize)

### Joining two numpy arrrays

In [3]:
x = np.array([1,2,3],dtype = np.uint8)
y = np.array([4,5,6],dtype = np.uint8)


In [50]:
z = np.stack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [54]:
z = np.stack((x,y),axis = 0)# Default
print(z)


[[1 2 3]
 [4 5 6]]


In [53]:
z = np.stack((x,y),axis = -1)# Default
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [2]:
import numpy as np
a = np.array([[200,300,400],[100,50,300]])
indices = np.where(a == a.max())
print(a[indices]) # prints [400]

# Index for max value found two times (two locations)
a = np.array([[200,400,400],[100,50,300]])
indices = np.where(a == a.max())
print(a[indices]) # prints [400 400] because two indices for max
#Now lets print the location (Index)
for index in indices:print(f)

[1 2 3 4 5 6]

    print(index)

[400]
[400 400]
[0 0]
[1 2]


## Finding index of max value in 2d numpy array

In [4]:
feature_cosine = np.array([[0.60297424,0.36831118,0.60297424,0.36831118,0.24039482,0.40173681,0.24039482,0.40173681,0.40720246,0.59291326,0.46257777],
 [0.48741489,0.45150006,0.48741489,0.45150006,0.16054236,0.48952348,0.16054236,0.48952348,0.49881946,0.43636624,0.51777843],
 [0.31060553,0.6216145,0.31060553,0.6216145,0.22986891,0.64508887,0.22986891,0.64508887,0.61993156,0.06545771,0.60227917]])
print(feature_cosine)

[[0.60297424 0.36831118 0.60297424 0.36831118 0.24039482 0.40173681
  0.24039482 0.40173681 0.40720246 0.59291326 0.46257777]
 [0.48741489 0.45150006 0.48741489 0.45150006 0.16054236 0.48952348
  0.16054236 0.48952348 0.49881946 0.43636624 0.51777843]
 [0.31060553 0.6216145  0.31060553 0.6216145  0.22986891 0.64508887
  0.22986891 0.64508887 0.61993156 0.06545771 0.60227917]]


In [15]:
print(feature_cosine[0,:]) # Entire 1st row  will get printed

[0.60297424 0.36831118 0.60297424 0.36831118 0.24039482 0.40173681
 0.24039482 0.40173681 0.40720246 0.59291326 0.46257777]


In [14]:
print(feature_cosine[1,:]) # Entire 1st row  will get printed

[0.48741489 0.45150006 0.48741489 0.45150006 0.16054236 0.48952348
 0.16054236 0.48952348 0.49881946 0.43636624 0.51777843]


In [21]:
for i, result_1 in enumerate (feature_cosine):
    max_value = np.amax(result_1)
    index = result_1.argmax()
    #max_value = np.amax(feature_cosimax_value = ne[i])
    print("index :",index)
    print("value :",max_value)

index : 0
value : 0.60297424
index : 10
value : 0.51777843
index : 5
value : 0.64508887


In [16]:
feature_cosine.max(axis=1)



array([0.60297424, 0.51777843, 0.64508887])

In [17]:
maxindex = feature_cosine.max(axis=1).argmax()
print(maxindex)

2


In [ ]:
def unique(list1):
    unique_list = []
    for x in list1:
        if x not in unique_list: 
            unique_list.append(x)
            del list1
            return unique_list 

## Converting List of ndarray in ndarray

In [ ]:
[[-0.027413018,-0.12505697,-0.04555426,-0.038284633,0.17099386,0.037258048,-0.098496504,-0.017346546,-0.076559156,-0.07366654,0.12928525,0.03011429,0.03799815,0.15459387,-0.09831122,-0.03410798,-0.08517328,0.036673095,-0.09683451,0.11160225,-0.005266203,0.12432646,-0.008817336,-0.06637519,-0.011291879,0.04544144,-0.063642204,-0.07031361,-0.05460893,-0.09521682,0.12615226,-0.033491313,0.030746885,-0.052866466,0.018702308,0.10678785,-0.06802289,-0.08942453,0.14427876,-0.1201506,-0.05041524,-0.054883324,-0.008762745,0.10230933,-0.04876626,-0.025659839,0.0707677,-0.060054604,-0.08357874,0.02422101,-0.067945346,-0.06957567,-0.04151485,0.09278792,0.13389027,-0.016498826,0.06086282,0.038578466,-0.0776168,-0.028419167,0.0064480696,-0.021257447,-0.053596333,-0.01985122,-0.06260821,0.17217001,0.04484105,-0.08158627,0.042076156,0.116868,0.010018134,-0.110815234,0.021451943,0.14311737,0.019695995,0.08878666,-0.1206503,0.043681778,-0.013750132,-0.112274915,0.064606294,-0.093218066,0.082909815,0.16213177,0.11682276,-0.005555807,0.026010199,0.09694614,-0.05359657,0.050320845,0.20713717,0.02721125,0.016239235,-0.07175786,0.31943277,-0.14783175,0.057573568,-0.025759852,-0.06644232,-0.119459614,0.006564804,-0.011508613,0.13815023,0.049904246,0.19772513,0.11592113,-0.039395016,-0.16275254,-0.013230952,-0.09308782,-0.06815189,-0.07023681,-0.015538157,0.1501475,-0.07171784,-0.061428506,-0.068844005,-0.08631256,0.035126608,0.013087853,-0.05355051,-0.050607763,0.08485801,-0.0833548,-0.15874106,-0.09535022,0.10557306,0.02931956,1.0]]


In [4]:
final = [[-0.027413018,-0.12505697,-0.04555426,-0.038284633,0.17099386,0.037258048,-0.098496504,-0.017346546,-0.076559156,-0.07366654,0.12928525,0.03011429,0.03799815,0.15459387,-0.09831122,-0.03410798,-0.08517328,0.036673095,-0.09683451,0.11160225,-0.005266203,0.12432646,-0.008817336,-0.06637519,-0.011291879,0.04544144,-0.063642204,-0.07031361,-0.05460893,-0.09521682,0.12615226,-0.033491313,0.030746885,-0.052866466,0.018702308,0.10678785,-0.06802289,-0.08942453,0.14427876,-0.1201506,-0.05041524,-0.054883324,-0.008762745,0.10230933,-0.04876626,-0.025659839,0.0707677,-0.060054604,-0.08357874,0.02422101,-0.067945346,-0.06957567,-0.04151485,0.09278792,0.13389027,-0.016498826,0.06086282,0.038578466,-0.0776168,-0.028419167,0.0064480696,-0.021257447,-0.053596333,-0.01985122,-0.06260821,0.17217001,0.04484105,-0.08158627,0.042076156,0.116868,0.010018134,-0.110815234,0.021451943,0.14311737,0.019695995,0.08878666,-0.1206503,0.043681778,-0.013750132,-0.112274915,0.064606294,-0.093218066,0.082909815,0.16213177,0.11682276,-0.005555807,0.026010199,0.09694614,-0.05359657,0.050320845,0.20713717,0.02721125,0.016239235,-0.07175786,0.31943277,-0.14783175,0.057573568,-0.025759852,-0.06644232,-0.119459614,0.006564804,-0.011508613,0.13815023,0.049904246,0.19772513,0.11592113,-0.039395016,-0.16275254,-0.013230952,-0.09308782,-0.06815189,-0.07023681,-0.015538157,0.1501475,-0.07171784,-0.061428506,-0.068844005,-0.08631256,0.035126608,0.013087853,-0.05355051,-0.050607763,0.08485801,-0.0833548,-0.15874106,-0.09535022,0.10557306,0.02931956,1.0]]
print(type(final))

<class 'list'>


In [2]:
import numpy as np
final_array = np.array(final)
print(final_array)

[[-0.02741302 -0.12505697 -0.04555426 -0.03828463  0.17099386  0.03725805
  -0.0984965  -0.01734655 -0.07655916 -0.07366654  0.12928525  0.03011429
   0.03799815  0.15459387 -0.09831122 -0.03410798 -0.08517328  0.0366731
  -0.09683451  0.11160225 -0.0052662   0.12432646 -0.00881734 -0.06637519
  -0.01129188  0.04544144 -0.0636422  -0.07031361 -0.05460893 -0.09521682
   0.12615226 -0.03349131  0.03074689 -0.05286647  0.01870231  0.10678785
  -0.06802289 -0.08942453  0.14427876 -0.1201506  -0.05041524 -0.05488332
  -0.00876275  0.10230933 -0.04876626 -0.02565984  0.0707677  -0.0600546
  -0.08357874  0.02422101 -0.06794535 -0.06957567 -0.04151485  0.09278792
   0.13389027 -0.01649883  0.06086282  0.03857847 -0.0776168  -0.02841917
   0.00644807 -0.02125745 -0.05359633 -0.01985122 -0.06260821  0.17217001
   0.04484105 -0.08158627  0.04207616  0.116868    0.01001813 -0.11081523
   0.02145194  0.14311737  0.019696    0.08878666 -0.1206503   0.04368178
  -0.01375013 -0.11227492  0.06460629 -0

In [10]:
flatList = []
for elem in final:
    flatList.extend(elem)
 
print('Flat List : ', flatList)

Flat List :  [-0.027413018, -0.12505697, -0.04555426, -0.038284633, 0.17099386, 0.037258048, -0.098496504, -0.017346546, -0.076559156, -0.07366654, 0.12928525, 0.03011429, 0.03799815, 0.15459387, -0.09831122, -0.03410798, -0.08517328, 0.036673095, -0.09683451, 0.11160225, -0.005266203, 0.12432646, -0.008817336, -0.06637519, -0.011291879, 0.04544144, -0.063642204, -0.07031361, -0.05460893, -0.09521682, 0.12615226, -0.033491313, 0.030746885, -0.052866466, 0.018702308, 0.10678785, -0.06802289, -0.08942453, 0.14427876, -0.1201506, -0.05041524, -0.054883324, -0.008762745, 0.10230933, -0.04876626, -0.025659839, 0.0707677, -0.060054604, -0.08357874, 0.02422101, -0.067945346, -0.06957567, -0.04151485, 0.09278792, 0.13389027, -0.016498826, 0.06086282, 0.038578466, -0.0776168, -0.028419167, 0.0064480696, -0.021257447, -0.053596333, -0.01985122, -0.06260821, 0.17217001, 0.04484105, -0.08158627, 0.042076156, 0.116868, 0.010018134, -0.110815234, 0.021451943, 0.14311737, 0.019695995, 0.08878666, -0.

In [6]:
DescriptorSize = 129
import numpy as np
final_array = np.array(final)
final_array = final_array.reshape(1,DescriptorSize)
print(final_array.shape)

(1, 129)


In [13]:
DescriptorSize = 129
re_collector =np.array([]).reshape(0,DescriptorSize-1)
final_ids =[]
final_ids=final_ids+final_array[:,DescriptorSize-1].astype(float).tolist()
final_ids = [round(x) for x in final_ids]
re_collector=final_array[:,0:DescriptorSize-1]
print("final_id :",final_ids)
print("re_collector :",re_collector)
r = re_collector

final_id : [1]
re_collector : [[-0.02741302 -0.12505697 -0.04555426 -0.03828463  0.17099386  0.03725805
  -0.0984965  -0.01734655 -0.07655916 -0.07366654  0.12928525  0.03011429
   0.03799815  0.15459387 -0.09831122 -0.03410798 -0.08517328  0.0366731
  -0.09683451  0.11160225 -0.0052662   0.12432646 -0.00881734 -0.06637519
  -0.01129188  0.04544144 -0.0636422  -0.07031361 -0.05460893 -0.09521682
   0.12615226 -0.03349131  0.03074689 -0.05286647  0.01870231  0.10678785
  -0.06802289 -0.08942453  0.14427876 -0.1201506  -0.05041524 -0.05488332
  -0.00876275  0.10230933 -0.04876626 -0.02565984  0.0707677  -0.0600546
  -0.08357874  0.02422101 -0.06794535 -0.06957567 -0.04151485  0.09278792
   0.13389027 -0.01649883  0.06086282  0.03857847 -0.0776168  -0.02841917
   0.00644807 -0.02125745 -0.05359633 -0.01985122 -0.06260821  0.17217001
   0.04484105 -0.08158627  0.04207616  0.116868    0.01001813 -0.11081523
   0.02145194  0.14311737  0.019696    0.08878666 -0.1206503   0.04368178
  -0.01375

In [8]:
for i in re_collector:
    print(i)

[-0.02741302 -0.12505697 -0.04555426 -0.03828463  0.17099386  0.03725805
 -0.0984965  -0.01734655 -0.07655916 -0.07366654  0.12928525  0.03011429
  0.03799815  0.15459387 -0.09831122 -0.03410798 -0.08517328  0.0366731
 -0.09683451  0.11160225 -0.0052662   0.12432646 -0.00881734 -0.06637519
 -0.01129188  0.04544144 -0.0636422  -0.07031361 -0.05460893 -0.09521682
  0.12615226 -0.03349131  0.03074689 -0.05286647  0.01870231  0.10678785
 -0.06802289 -0.08942453  0.14427876 -0.1201506  -0.05041524 -0.05488332
 -0.00876275  0.10230933 -0.04876626 -0.02565984  0.0707677  -0.0600546
 -0.08357874  0.02422101 -0.06794535 -0.06957567 -0.04151485  0.09278792
  0.13389027 -0.01649883  0.06086282  0.03857847 -0.0776168  -0.02841917
  0.00644807 -0.02125745 -0.05359633 -0.01985122 -0.06260821  0.17217001
  0.04484105 -0.08158627  0.04207616  0.116868    0.01001813 -0.11081523
  0.02145194  0.14311737  0.019696    0.08878666 -0.1206503   0.04368178
 -0.01375013 -0.11227492  0.06460629 -0.09321807  0.0

In [22]:
if np.array_equal(np.array([1, 2]), np.array([1, 4])):
    print("true")
else :
    print("false")


false


In [1]:
cam2_features = [ 0.23769951, -0.06237032, -0.01308929, -0.04274568,  0.12196711, -0.04702076,
  0.03825378,  0.02307336,  0.01057977,  0.04053931, -0.144039,    0.01166391,
  0.05392008,  0.11714651, -0.06440976, -0.06020599,  0.10156408,  0.02019679,
  0.02985681,  0.03250476, -0.01972423,  0.08643089, -0.02874772,  0.07200889,
 -0.09144391, -0.04913371, -0.06785882, -0.01427083, -0.11163063, -0.05557281,
  0.02713554,  0.00275645,  0.07760818, -0.12323337,  0.03357118,  0.07758798,
  0.24414195, -0.09929942,  0.03920833, -0.14932574, -0.07309262,  0.03763754,
 -0.10107876,  0.06374996, -0.00321028,  0.05842426,  0.13100412, -0.08730327,
  0.02860511, -0.08014176, -0.13302647, -0.06963421, -0.10419498,  0.00327254,
  0.12506017,  0.10943376, -0.1646866,   0.00859577, -0.00144971, -0.00539653,
  0.03154421, -0.04868154, -0.06831024, -0.05461941, -0.02371174, -0.07833408,
  0.00778448, -0.06600067, -0.0443739,   0.06344783, -0.00498846, -0.10209183,
 -0.15137845, -0.09092538,  0.07679182,  0.07563247, -0.12118237, -0.01577256,
 -0.0442051,  -0.06734487,  0.14123185, -0.09691659, -0.11524443,  0.09383,
  0.03274136, -0.10101283,  0.12347609,  0.0531556,  -0.02692899, -0.17734128,
  0.00069806,  0.06727875,  0.1936462,  -0.10911909,  0.21232496, -0.10353576,
 -0.01098319, -0.04898298, -0.0013687,  -0.11765876, -0.02370896, -0.08758633,
 -0.10596856, -0.06209955, -0.0794651, -0.02407027, -0.04466186, -0.15161408,
 -0.14892189, -0.05323831, -0.13918883, -0.00720938,  0.08306113, -0.01289514,
  0.07543588, -0.14237818, -0.04317758, -0.08673432, -0.01706154, -0.09636802,
 -0.12392074, -0.12249604,  0.02216491, -0.07482912, -0.08287387, -0.09358601,
  0.02956846, -0.01289933]

In [2]:
recollector = [ 0.23769951, -0.06237032, -0.01308929, -0.04274568,  0.12196711, -0.04702076,
  0.03825378,  0.02307336,  0.01057977,  0.04053931, -0.144039,    0.01166391,
  0.05392008,  0.11714651, -0.06440976, -0.06020599,  0.10156408,  0.02019679,
  0.02985681,  0.03250476, -0.01972423,  0.08643089, -0.02874772,  0.07200889,
 -0.09144391, -0.04913371, -0.06785882, -0.01427083, -0.11163063, -0.05557281,
  0.02713554,  0.00275645,  0.07760818, -0.12323337,  0.03357118,  0.07758798,
  0.24414195, -0.09929942,  0.03920833, -0.14932574, -0.07309262,  0.03763754,
 -0.10107876,  0.06374996, -0.00321028,  0.05842426,  0.13100412, -0.08730327,
  0.02860511, -0.08014176, -0.13302647, -0.06963421, -0.10419498,  0.00327254,
  0.12506017,  0.10943376, -0.1646866,   0.00859577, -0.00144971, -0.00539653,
  0.03154421, -0.04868154, -0.06831024, -0.05461941, -0.02371174, -0.07833408,
  0.00778448, -0.06600067, -0.0443739,   0.06344783, -0.00498846, -0.10209183,
 -0.15137845, -0.09092538,  0.07679182,  0.07563247, -0.12118237, -0.01577256,
 -0.0442051,  -0.06734487,  0.14123185, -0.09691659, -0.11524443,  0.09383,
  0.03274136, -0.10101283,  0.12347609,  0.0531556,  -0.02692899, -0.17734128,
  0.00069806,  0.06727875,  0.1936462,  -0.10911909,  0.21232496, -0.10353576,
 -0.01098319, -0.04898298, -0.0013687,  -0.11765876, -0.02370896, -0.08758633,
 -0.10596856, -0.06209955, -0.0794651, -0.02407027, -0.04466186, -0.15161408,
 -0.14892189, -0.05323831, -0.13918883, -0.00720938,  0.08306113, -0.01289514,
  0.07543588, -0.14237818, -0.04317758, -0.08673432, -0.01706154, -0.09636802,
 -0.12392074, -0.12249604,  0.02216491, -0.07482912, -0.08287387, -0.09358601,
  0.02956846, -0.01289933]


In [13]:
import numpy as np
final_array1 = np.array(cam2_features)
final_array2 = np.array(recollector)
print(type(final_array1))
print(type(final_array2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
final_array1.dtype
final_array2.dtype

dtype('float64')

In [15]:
final_array1 = np.float32(final_array1)
final_array2 = np.float32(final_array2)
print(final_array1.dtype)


float32


In [14]:
if np.array_equal(final_array1,final_array2):
    print("true")
else :
    print("false")
    

true


In [30]:
subracted_array = i-r

In [31]:
print("subracted_array",subracted_array)

subracted_array [[ 2.65112528e-01  6.26866500e-02  3.24649700e-02 -4.46104700e-03
  -4.90267500e-02 -8.42788080e-02  1.36750284e-01  4.04199060e-02
   8.71389260e-02  1.14205850e-01 -2.73324250e-01 -1.84503800e-02
   1.59219300e-02 -3.74473600e-02  3.39014600e-02 -2.60980100e-02
   1.86737360e-01 -1.64763050e-02  1.26691320e-01 -7.90974900e-02
  -1.44580270e-02 -3.78955700e-02 -1.99303840e-02  1.38384080e-01
  -8.01520310e-02 -9.45751500e-02 -4.21661600e-03  5.60427800e-02
  -5.70217000e-02  3.96440100e-02 -9.90167200e-02  3.62477630e-02
   4.68612950e-02 -7.03669040e-02  1.48688720e-02 -2.91998700e-02
   3.12164840e-01 -9.87489000e-03 -1.05070430e-01 -2.91751400e-02
  -2.26773800e-02  9.25208640e-02 -9.23160150e-02 -3.85593700e-02
   4.55559800e-02  8.40840990e-02  6.02364200e-02 -2.72486660e-02
   1.12183850e-01 -1.04362770e-01 -6.50811240e-02 -5.85400000e-05
  -6.26801300e-02 -8.95153800e-02 -8.83010000e-03  1.25932586e-01
  -2.25549420e-01 -2.99826960e-02  7.61670900e-02  2.3022637

In [33]:
absoulte_array = abs(subracted_array)
print("absoulte_array",absoulte_array)

absoulte_array [[2.65112528e-01 6.26866500e-02 3.24649700e-02 4.46104700e-03
  4.90267500e-02 8.42788080e-02 1.36750284e-01 4.04199060e-02
  8.71389260e-02 1.14205850e-01 2.73324250e-01 1.84503800e-02
  1.59219300e-02 3.74473600e-02 3.39014600e-02 2.60980100e-02
  1.86737360e-01 1.64763050e-02 1.26691320e-01 7.90974900e-02
  1.44580270e-02 3.78955700e-02 1.99303840e-02 1.38384080e-01
  8.01520310e-02 9.45751500e-02 4.21661600e-03 5.60427800e-02
  5.70217000e-02 3.96440100e-02 9.90167200e-02 3.62477630e-02
  4.68612950e-02 7.03669040e-02 1.48688720e-02 2.91998700e-02
  3.12164840e-01 9.87489000e-03 1.05070430e-01 2.91751400e-02
  2.26773800e-02 9.25208640e-02 9.23160150e-02 3.85593700e-02
  4.55559800e-02 8.40840990e-02 6.02364200e-02 2.72486660e-02
  1.12183850e-01 1.04362770e-01 6.50811240e-02 5.85400000e-05
  6.26801300e-02 8.95153800e-02 8.83010000e-03 1.25932586e-01
  2.25549420e-01 2.99826960e-02 7.61670900e-02 2.30226370e-02
  2.50961404e-02 2.74240930e-02 1.47139070e-02 3.476819

In [34]:
mean_value = np.mean(absoulte_array)
print("mean_value",mean_value)

mean_value 0.07483028733125
