<img src="numpy.png"
     align="right"
     width="30%"
     alt="Python logo\">

# NumPy Package in Python

NumPy is an open source library available in Python that aids in mathematical, scientific, engineering, and data science programming. NumPy is an incredible library to perform mathematical and statistical operations. It works perfectly well for multi-dimensional arrays and matrices multiplication

- Fundamental package for scientific computing with Python
- It has a powerful N-dimensional Array Object called as ndarray and routine to manipulate it
- It also has other derived objects like masked arrays ans matrices
- NumPy is used by other libraries like Scipy, matplotlib, OpenCV, Scikit-image,Scikit learn, pandas to store the multi-dimensional data.

**For Example** -: numpy provides ndarray to store image and that can be manipulate accordingly


## Why use NumPy?

- NumPy is memory efficiency, meaning it can handle the vast amount of data more accessible than any other library.
- Besides, NumPy is very convenient to work with, especially for matrix multiplication and reshaping.On top of that, NumPy is fast. 
- In fact, TensorFlow and Scikit learn to use NumPy array to compute the matrix multiplication in the back end.

#### N-Dimensional array(ndarray) in Numpy

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

In [2]:
# Python program to demonstrate 
# basic array characteristics
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


### Array Creation

There are various ways to create arrays in NumPy.

- For example, you can create an array from a regular Python **list** or **tuple** using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.
- Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.
  For example: np.zeros, np.ones, np.full, np.empty, etc.
- **arange:** returns evenly spaced values within a given interval. step size is specified.
- **linspace:** returns evenly spaced values within a given interval. num no. of elements are returned.
- **Reshaping array:** We can use reshape method to reshape an array. Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into another array with shape (b1, b2, b3, …, bM). The only required condition is: 
  a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM . (i.e original size of array remains unchanged.)
- **Flatten array:** We can use flatten method to get a copy of array collapsed into one dimension. It accepts order argument. Default value is ‘C’ (for row-major order). Use ‘F’ for column major order.

In [1]:
# Python program to demonstrate
# array creation techniques
import numpy as np
 
# Creating array from list with type float
list1 = [[1, 2, 4],[5, 6, 7]]
a = np.array(list1, dtype = 'float')
print ("Array created using passed list:\n", a)
 
# Creating array from tuple
tuple1 = (1 , 3, 2)
b = np.array(tuple1)
print ("\nArray created using passed tuple:\n", b)
 
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)
 
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
            "Array type is complex:\n", d)

Array created using passed list:
 [[1. 2. 4.]
 [5. 6. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


### Array Indexing

Knowing the basics of array indexing is important for analysing and manipulating the array object. NumPy offers many ways to do array indexing.

- **Slicing:** Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.
- **Integer array indexing:** In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.
- **Boolean array indexing:** This method is used when we want to pick elements from array which satisfy some condition.

In [ ]:
# Python program to demonstrate
# indexing in numpy
import numpy as np
 
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
 
# Slicing array

temp = arr[:,0]
print("Array with first column:\n",temp)

temp = arr[0, :]
print("Array with first row:\n",temp)

temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)
 
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
 
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

## Numpy ndarray properties

In [13]:
#A 3-dimensional array of size 3 x 3 x 3, composed of 2-byte integer elements:

x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                  [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [22]:
print("Shape of array :",x.shape)
print("No. of Dimensions :",x.ndim)
print("Array type :",type(x))
print("data type :",x.dtype)
print("size :",x.size)
print("bytes consumed :",x.nbytes)

Shape of array : (3, 3, 3)
No. of Dimensions : 3
Array type : <class 'numpy.ndarray'>
data type : int32
size : 27
bytes consumed : 108


In [23]:
print("Transpose of Array :",x.T)

Transpose of Array : [[[ 1 10 10]
  [ 4 13 13]
  [ 7 16 16]]

 [[ 2 11 11]
  [ 5 14 14]
  [ 8 17 17]]

 [[ 3 12 12]
  [ 6 15 15]
  [ 9 18 18]]]


## Scientific Constants

In [26]:
print(np.inf)
print(np.NAN)
print(np.NINF)
print(np.NZERO)
print(np.PZERO)
print(np.e)
print(np.euler_gamma)
print(np.pi)

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


## Ones and Zeros

In [2]:
import numpy as np

x = np.empty([3,3], np.uint8)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
#creates an array with diagonal elements are 1
y = np.eye(3, dtype=np.uint8)
print(y)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [8]:
y1 = np.eye(5, dtype=np.uint8, k=1) # position of 1 shift upward
y2 = np.eye(5, dtype=np.uint8, k=-1) # position of 1 shift downward
print(y1,"\n")
print(y2)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]] 

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [10]:
# creates matrices of all ones
x = np.ones((2,5,5), dtype=np.int16)
print(x)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [13]:
# create matrx of specific dimension filled with user define number.
x = np.full((3,3,3),dtype=np.int16, fill_value =3)
print(x)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]


## Matrix creation routines

In [15]:
x = np.tri(5,5, k=-1,dtype=np.uint16)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [16]:
x = np.tri(5,5, k=1,dtype=np.uint16)
print(x)

[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [19]:
x= np.ones((5,5), dtype=np.uint8)
y= np.tril(x, k=0)
print(y)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


## Creating Random Arrays

In [20]:
import numpy as np


In [21]:
# single dimensional ndarray of random integers in random order
x = np.random.randint( low = 0, high =9, size = 10) # use in signal processing having some sort of random noise 
print(x)

[7 7 3 5 8 4 7 0 8 8]


In [23]:
# multi dimensional ndarray  in random order
x =np.random.rand(3,3,3)
print(x)

[[[0.46735155 0.62661996 0.73425841]
  [0.66173012 0.61649951 0.38652719]
  [0.20350949 0.77344082 0.02363505]]

 [[0.85724543 0.47994644 0.44641774]
  [0.92342035 0.43088488 0.75876901]
  [0.47514119 0.38085809 0.66408282]]

 [[0.44799776 0.09744467 0.2163089 ]
  [0.18486436 0.22467432 0.33806239]
  [0.14043811 0.7588398  0.37365767]]]


## Array Manipulation 

In [26]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [27]:
y = x.reshape((3,2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [31]:
x =np.array([[0,1,2],[3,4,5]],dtype=np.uint16)
print(x)

[[0 1 2]
 [3 4 5]]


In [30]:
y = np.reshape(x,6)
print(y)

[0 1 2 3 4 5]


In [33]:
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


#### Flatten

In [34]:

y = x.flatten('C') # or y = x.flatten() --> row wise
print(y)

[0 1 2 3 4 5]


In [35]:
y = x.flatten('F') # column wise
print(y)

[0 3 1 4 2 5]


**Application** - These are useful in image processing to flatten a 2d image into a linear image for adjusting the histogram. 

In [63]:
x = np.array([1,2,3], dtype = np.uint8)
y = np.array([4,5,6], dtype = np.uint8)

print(x.dtype)
print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


uint8 saves a lot of spaces specially for low memory devices like raspberry or embedded box

#### Stack

In [64]:
# Combining two matrices using stack
z = np.stack((x,y), axis = 0)
print(z)

[[1 2 3]
 [4 5 6]]


In [65]:
z = np.dstack((x,y)) # depth wise 
print(z)
print("dimension :",z.ndim)

[[[1 4]
  [2 5]
  [3 6]]]
dimension : 3


In [51]:
z = np.hstack((x,y))# horizontal wise
print(z)
print("dimension :",z.ndim)

[1 2 3 4 5 6]
dimension : 1


#### Split

In [53]:
x = np.arange(9)
print(x)

a,b,c = np.split(x,3)
print(a, b, c)

[0 1 2 3 4 5 6 7 8]
[0 1 2] [3 4 5] [6 7 8]


In [67]:
x = np.random.rand(4, 4, 4)
print(x)


[[[0.46140686 0.6830367  0.82369783 0.60930171]
  [0.05049667 0.47966233 0.16316535 0.55782333]
  [0.4865678  0.00671195 0.57155277 0.9674734 ]
  [0.56329689 0.77052127 0.0810892  0.02500201]]

 [[0.7010874  0.04289411 0.87348696 0.02899563]
  [0.69348287 0.99630842 0.76737088 0.70457698]
  [0.51323594 0.97878266 0.14323835 0.56009832]
  [0.25794749 0.52841618 0.34195005 0.32040498]]

 [[0.9022743  0.59177135 0.10095516 0.08783293]
  [0.25361484 0.99727574 0.26891705 0.03014457]
  [0.03954412 0.95528096 0.90992261 0.73893399]
  [0.66196484 0.77322811 0.614282   0.579423  ]]

 [[0.37621145 0.27681821 0.7757313  0.98479359]
  [0.06541976 0.13143074 0.59325866 0.51543907]
  [0.86004584 0.29407988 0.91109064 0.48193942]
  [0.10734769 0.87056716 0.77687437 0.60205857]]]


In [68]:
y, z = np.split(x, 2)
print(y , z)

[[[0.46140686 0.6830367  0.82369783 0.60930171]
  [0.05049667 0.47966233 0.16316535 0.55782333]
  [0.4865678  0.00671195 0.57155277 0.9674734 ]
  [0.56329689 0.77052127 0.0810892  0.02500201]]

 [[0.7010874  0.04289411 0.87348696 0.02899563]
  [0.69348287 0.99630842 0.76737088 0.70457698]
  [0.51323594 0.97878266 0.14323835 0.56009832]
  [0.25794749 0.52841618 0.34195005 0.32040498]]] [[[0.9022743  0.59177135 0.10095516 0.08783293]
  [0.25361484 0.99727574 0.26891705 0.03014457]
  [0.03954412 0.95528096 0.90992261 0.73893399]
  [0.66196484 0.77322811 0.614282   0.579423  ]]

 [[0.37621145 0.27681821 0.7757313  0.98479359]
  [0.06541976 0.13143074 0.59325866 0.51543907]
  [0.86004584 0.29407988 0.91109064 0.48193942]
  [0.10734769 0.87056716 0.77687437 0.60205857]]]


In [69]:
y, z = np.dsplit(x, 2) # Splitting according to depth
print(y , z)

[[[0.46140686 0.6830367 ]
  [0.05049667 0.47966233]
  [0.4865678  0.00671195]
  [0.56329689 0.77052127]]

 [[0.7010874  0.04289411]
  [0.69348287 0.99630842]
  [0.51323594 0.97878266]
  [0.25794749 0.52841618]]

 [[0.9022743  0.59177135]
  [0.25361484 0.99727574]
  [0.03954412 0.95528096]
  [0.66196484 0.77322811]]

 [[0.37621145 0.27681821]
  [0.06541976 0.13143074]
  [0.86004584 0.29407988]
  [0.10734769 0.87056716]]] [[[0.82369783 0.60930171]
  [0.16316535 0.55782333]
  [0.57155277 0.9674734 ]
  [0.0810892  0.02500201]]

 [[0.87348696 0.02899563]
  [0.76737088 0.70457698]
  [0.14323835 0.56009832]
  [0.34195005 0.32040498]]

 [[0.10095516 0.08783293]
  [0.26891705 0.03014457]
  [0.90992261 0.73893399]
  [0.614282   0.579423  ]]

 [[0.7757313  0.98479359]
  [0.59325866 0.51543907]
  [0.91109064 0.48193942]
  [0.77687437 0.60205857]]]


In [70]:
y, z = np.vsplit(x, 2) # Splitting vertically
print(y , z)

[[[0.46140686 0.6830367  0.82369783 0.60930171]
  [0.05049667 0.47966233 0.16316535 0.55782333]
  [0.4865678  0.00671195 0.57155277 0.9674734 ]
  [0.56329689 0.77052127 0.0810892  0.02500201]]

 [[0.7010874  0.04289411 0.87348696 0.02899563]
  [0.69348287 0.99630842 0.76737088 0.70457698]
  [0.51323594 0.97878266 0.14323835 0.56009832]
  [0.25794749 0.52841618 0.34195005 0.32040498]]] [[[0.9022743  0.59177135 0.10095516 0.08783293]
  [0.25361484 0.99727574 0.26891705 0.03014457]
  [0.03954412 0.95528096 0.90992261 0.73893399]
  [0.66196484 0.77322811 0.614282   0.579423  ]]

 [[0.37621145 0.27681821 0.7757313  0.98479359]
  [0.06541976 0.13143074 0.59325866 0.51543907]
  [0.86004584 0.29407988 0.91109064 0.48193942]
  [0.10734769 0.87056716 0.77687437 0.60205857]]]


In [71]:
 y, z = np.hsplit(x, 2) # Splitting horizentally
print(y , z)

[[[0.46140686 0.6830367  0.82369783 0.60930171]
  [0.05049667 0.47966233 0.16316535 0.55782333]]

 [[0.7010874  0.04289411 0.87348696 0.02899563]
  [0.69348287 0.99630842 0.76737088 0.70457698]]

 [[0.9022743  0.59177135 0.10095516 0.08783293]
  [0.25361484 0.99727574 0.26891705 0.03014457]]

 [[0.37621145 0.27681821 0.7757313  0.98479359]
  [0.06541976 0.13143074 0.59325866 0.51543907]]] [[[0.4865678  0.00671195 0.57155277 0.9674734 ]
  [0.56329689 0.77052127 0.0810892  0.02500201]]

 [[0.51323594 0.97878266 0.14323835 0.56009832]
  [0.25794749 0.52841618 0.34195005 0.32040498]]

 [[0.03954412 0.95528096 0.90992261 0.73893399]
  [0.66196484 0.77322811 0.614282   0.579423  ]]

 [[0.86004584 0.29407988 0.91109064 0.48193942]
  [0.10734769 0.87056716 0.77687437 0.60205857]]]


#### Flip

In [74]:
x = np.arange(16).reshape(4,4)
print(x)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [79]:
y = np.flip(x, axis = -1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [78]:
y = np.flip(x, axis = 0) # mirror image
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
